using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using csDBPF;

namespace SC4ModdingSuite.Models;

/// <summary>
/// Thin wrapper around csDBPF's <see cref="DBPFFile"/> that exposes only what the
/// TGI editor UI needs: open/create/save a package, list its entries, remove an entry,
/// and change an entry's Group/Instance IDs (optionally generating them randomly).
/// </summary>
public sealed class DbpfService
{
    /// <summary>The package currently loaded (or newly created), if any.</summary>
    public DBPFFile? CurrentFile { get; private set; }

    /// <summary>
    /// Entries added or modified since the package was opened (Ilive Reader's own
    /// "Recorder"/Patch Manager - <c>CSave::m_aRecorded</c>) - a running set of "what
    /// changed this session", so a patch containing just those entries can be exported
    /// without hand-picking them. Cleared on Open/CreateNew; entries removed via
    /// RemoveEntry drop out too (nothing to patch-export for something no longer there).
    /// </summary>
    public HashSet<DBPFEntry> RecordedEntries { get; } = new();

    /// <summary>Full path of the currently loaded package, or null for an unsaved new package.</summary>
    public string? CurrentPath { get; private set; }

    public bool HasOpenFile => CurrentFile is not null;

    /// <summary>All entries (subfiles) currently in the package.</summary>
    public IReadOnlyList<DBPFEntry> Entries =>
        CurrentFile is null ? Array.Empty<DBPFEntry>() : CurrentFile.ListOfEntries.ToList();

    /// <summary>Opens an existing SC4 DBPF-format file (.dat/.sc4lot/.sc4desc/.sc4model).</summary>
    public void Open(string path)
    {
        RecordedEntries.Clear();
        CurrentFile = new DBPFFile(path);
        CurrentPath = path;
    }

    /// <summary>Starts a brand-new, empty package in memory.</summary>
    public void CreateNew()
    {
        RecordedEntries.Clear();
        CurrentFile = new DBPFFile();
        CurrentPath = null;
    }

    /// <summary>Removes the given entry from the currently open package.</summary>
    public void RemoveEntry(DBPFEntry entry)
    {
        if (CurrentFile is null)
        {
            return;
        }

        DbpfFileFixes.RemoveEntry(CurrentFile, entry.TGI);
        RecordedEntries.Remove(entry);
    }

    /// <summary>
    /// Changes an entry's TGI. Type ID is set manually only (never randomized, per design:
    /// randomizing the format identifier could easily produce a nonsensical/corrupt entry).
    /// Group and Instance can each independently be set to an explicit value or regenerated
    /// randomly.
    /// </summary>
    /// <param name="entry">Entry to modify (must belong to <see cref="CurrentFile"/>).</param>
    /// <param name="newType">New Type ID to use. Always applied literally, never randomized.</param>
    /// <param name="newGroup">New Group ID to use; ignored if <paramref name="randomizeGroup"/> is true.</param>
    /// <param name="newInstance">New Instance ID to use; ignored if <paramref name="randomizeInstance"/> is true.</param>
    /// <param name="randomizeGroup">If true, a new random Group ID is generated.</param>
    /// <param name="randomizeInstance">If true, a new random Instance ID is generated.</param>
    /// <returns>
    /// The new <see cref="DBPFEntry"/> instance that replaced <paramref name="entry"/> in the
    /// package (since TGI is read-only, changing it means swapping in a fresh entry object
    /// with the same payload bytes but a different TGI). Callers must stop using the old
    /// entry reference and switch to this one.
    /// </returns>
    public DBPFEntry ChangeEntryTgi(
        DBPFEntry entry,
        uint newType,
        uint newGroup,
        uint newInstance,
        bool randomizeGroup,
        bool randomizeInstance)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var current = entry.TGI;

        // Random Group/Instance values are generated by TgiGenerator (matching Ilive
        // Reader's own CoCreateGuid-based algorithm exactly - see that class for details)
        // instead of relying on csDBPF's own TGI(t, g, i) constructor auto-generating a
        // value when passed 0: csDBPF ships as a compiled DLL with no available source, so
        // there's no way to confirm its internal algorithm matches Ilive Reader's, and it
        // almost certainly doesn't (GUID-derived vs. some undocumented alternative). Type
        // ID is always taken literally, never randomized, as requested.
        uint groupToUse = randomizeGroup ? TgiGenerator.GenerateRandomId() : newGroup;
        uint instanceToUse = randomizeInstance ? TgiGenerator.GenerateRandomId() : newInstance;

        var updated = new TGI(newType, groupToUse, instanceToUse);

        // DBPFEntry.TGI is read-only: csDBPF entries are identified by their TGI for
        // their whole lifetime. To "change" it we recreate an entry of the same
        // concrete type (DBPFEntryEXMP, DBPFEntryLTEXT, DBPFEntryPNG, ...) carrying the
        // exact same raw bytes/offset/index but the new TGI, then swap it into the file.
        // All concrete entry types share the constructor pattern
        // (TGI tgi, uint offset, uint size, uint index, byte[] bytes), so this is done
        // generically via reflection instead of a big type switch.
        var entryType = entry.GetType();
        var ctor = FindReadingConstructor(entryType);

        if (ctor is null)
        {
            throw new NotSupportedException(
                $"Entries of type '{entryType.Name}' do not support changing the TGI " +
                "(this is probably the package's internal Directory entry, which has a fixed TGI).");
        }

        object[] args =
        {
            updated,
            DbpfWriter.ToUInt32(entry.Offset),
            DbpfWriter.ToUInt32(entry.GetSize()),
            DbpfWriter.ToUInt32(entry.IndexPos),
            entry.ByteData ?? Array.Empty<byte>(),
        };

        var newEntry = (DBPFEntry)ctor.Invoke(args);

        DbpfFileFixes.RemoveEntry(CurrentFile, current);
        CurrentFile.AddEntry(newEntry);
        RecordedEntries.Remove(entry);
        RecordedEntries.Add(newEntry);

        return newEntry;
    }

    /// <summary>
    /// Finds the "reading an existing entry" constructor
    /// <c>(TGI tgi, uint offset, uint size, uint index, byte[] bytes)</c> shared by every
    /// concrete <see cref="DBPFEntry"/> subtype, searching <b>public and non-public</b>
    /// constructors alike. The non-public search matters specifically for
    /// <c>DBPFEntryUnknown</c> - csDBPF's own generic/fallback entry type for anything it
    /// doesn't have a structured decoder for - which is an <c>internal</c> class with no
    /// documented public constructor; without <see cref="BindingFlags.NonPublic"/>,
    /// reflection can never find it, and every operation that needs to recreate an entry
    /// (TGI changes, byte replacement, pasting copied entries) would silently fail for any
    /// entry csDBPF doesn't otherwise recognize. .NET reflection is allowed to invoke
    /// non-public constructors from outside the declaring assembly as long as the caller
    /// explicitly asks for them this way - no special assembly attribute needed on
    /// csDBPF's side.
    /// </summary>
    private static ConstructorInfo? FindReadingConstructor(Type entryType) =>
        entryType.GetConstructor(
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance,
            binder: null,
            new[] { typeof(TGI), typeof(uint), typeof(uint), typeof(uint), typeof(byte[]) },
            modifiers: null);

    /// <summary>
    /// Creates and adds a brand-new entry (not derived from any entry already in this
    /// package) from a TGI and raw bytes, as if it had just been read from a file with
    /// that content - used to paste entries copied from a different package (see
    /// <see cref="Models.EntryClipboard"/>). <paramref name="concreteTypeName"/> is the
    /// <see cref="Type.AssemblyQualifiedName"/> of the entry's original concrete csDBPF
    /// type (captured at copy time), resolved back via <see cref="FindReadingConstructor"/>
    /// so the pasted entry gets exactly the same structured behavior (image decode,
    /// LTEXT text, Exemplar properties, ...) it had in its source package.
    /// </summary>
    /// <returns>The new entry, or null if the type couldn't be resolved/constructed (the caller should skip it).</returns>
    public DBPFEntry? AddEntryFromClipboard(string concreteTypeName, TGI tgi, byte[] bytes)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var entryType = Type.GetType(concreteTypeName);
        if (entryType is null)
        {
            return null;
        }

        var ctor = FindReadingConstructor(entryType);
        if (ctor is null)
        {
            return null;
        }

        object[] args = { tgi, 0u, (uint)bytes.Length, 0u, bytes };
        var newEntry = (DBPFEntry)ctor.Invoke(args);

        DbpfFileFixes.AddOrUpdateEntry(CurrentFile, newEntry);
        RecordedEntries.Add(newEntry);
        return newEntry;
    }

    /// <summary>
    /// Creates or updates an LTEXT entry at the exact <paramref name="tgi"/> given, setting
    /// its text to <paramref name="text"/> - the one write path shared by the LTEXT
    /// Editor's "SAVE FILE", "SAVE ALL FOR LANGUAGE" and "IMPORT POEDIT" actions, all of
    /// which need to place a translated string at a specific language-offset TGI (see
    /// <see cref="LtextTgiLanguage"/>) whether or not an entry already happens to exist
    /// there yet.
    /// </summary>
    /// <returns>The created or updated <see cref="DBPFEntryLTEXT"/>.</returns>
    public DBPFEntryLTEXT UpsertLtextEntry(TGI tgi, string text)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var existing = CurrentFile.GetEntry(tgi);

        DBPFEntryLTEXT ltext;
        if (existing is DBPFEntryLTEXT existingLtext)
        {
            existingLtext.Text = text;
            ltext = existingLtext;
        }
        else
        {
            // A brand-new entry, or an existing non-LTEXT entry (e.g. csDBPF's generic
            // DBPFEntryUnknown for something this app hasn't touched yet) at that TGI -
            // either way, a fresh DBPFEntryLTEXT is what should live there afterwards.
            ltext = new DBPFEntryLTEXT(tgi, text);
        }

        ltext.Encode(compress: false);
        DbpfFileFixes.AddOrUpdateEntry(CurrentFile, ltext);
        RecordedEntries.Add(ltext);
        return ltext;
    }

    /// <summary>Looks up an entry by its exact TGI, or null if none exists at that address yet.</summary>
    public DBPFEntry? TryGetEntry(TGI tgi) => CurrentFile?.GetEntry(tgi);

    /// <summary>
    /// Saves the package back to the file it was opened from. Writes the package with
    /// <see cref="DbpfWriter"/> (a from-scratch, correct DBPF writer ported from Ilive
    /// Reader) instead of csDBPF's own <c>DBPFFile.Save()</c>, which produced corrupted
    /// files once entries had been swapped out via <see cref="ChangeEntryTgi"/>.
    ///
    /// Refuses to overwrite one of SC4's core game data files (see
    /// <see cref="ProtectedFileNames"/>) even if somehow invoked - <see cref="CanSaveInPlace"/>
    /// already keeps the "Save" button disabled for these, this is defense in depth.
    /// </summary>
    public void Save()
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        if (CurrentPath is null)
        {
            throw new InvalidOperationException("Package has no associated path; use SaveAs instead.");
        }

        if (ProtectedFileNames.IsProtected(CurrentPath))
        {
            throw new InvalidOperationException(
                "This is a protected SC4 system file: use \"Save As...\" to create a new file.");
        }

        DbpfWriter.WritePackage(CurrentFile.ListOfEntries, CurrentPath);
    }

    /// <summary>
    /// Result of <see cref="ExportRhdToLhd"/>: how many T21 exemplars were actually
    /// mirrored, vs. how many entries (T21 or not) were carried over unchanged into the
    /// new file because they either weren't a T21 at all or weren't a well-formed one
    /// (<see cref="T21LhdConverter.MirrorToLhd"/> returned null - copied through as-is
    /// instead of being dropped, so the new file is never missing anything the source had).
    /// </summary>
    public sealed record RhdToLhdResult(int Mirrored, int CopiedUnchanged);

    /// <summary>
    /// Writes a brand-new file at <paramref name="path"/> containing every entry from the
    /// currently open package, with every T21 (network lot / Prop&amp;Flora placement)
    /// Exemplar mirrored for left-hand-drive traffic (see <see cref="T21LhdConverter"/> for
    /// exactly what "mirrored" means) - the requested "RHD → LHD" conversion. The
    /// currently open package itself (<see cref="CurrentFile"/>/<see cref="CurrentPath"/>)
    /// is never modified; this only ever reads from it and writes a separate file, exactly
    /// like <see cref="SaveAs"/> but with T21 entries transformed along the way instead of
    /// copied byte-for-byte.
    /// </summary>
    public RhdToLhdResult ExportRhdToLhd(string path)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var mirroredCount = 0;
        var copiedCount = 0;
        var outputEntries = new List<DBPFEntry>();

        foreach (var entry in CurrentFile.ListOfEntries)
        {
            if (entry is DBPFEntryEXMP exemplar && T21LhdConverter.IsT21Exemplar(exemplar))
            {
                var mirrored = T21LhdConverter.MirrorToLhd(exemplar);
                if (mirrored is not null)
                {
                    outputEntries.Add(mirrored);
                    mirroredCount++;
                    continue;
                }
            }

            outputEntries.Add(entry);
            copiedCount++;
        }

        DbpfWriter.WritePackage(outputEntries, path);
        return new RhdToLhdResult(mirroredCount, copiedCount);
    }

    /// <summary>
    /// Saves the package to a new file path, creating it if needed. See <see cref="Save"/>
    /// for why this uses <see cref="DbpfWriter"/> instead of csDBPF's own SaveAs. Unlike
    /// <see cref="Save"/>, this is always allowed even for a package originally opened
    /// from a protected file name - "Save As..." to a *different* file/name is
    /// exactly the escape hatch <see cref="ProtectedFileNames"/> exists to force.
    /// </summary>
    public void SaveAs(string path)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        DbpfWriter.WritePackage(CurrentFile.ListOfEntries, path);
        CurrentPath = path;
    }

    /// <summary>
    /// True if the package can be saved directly: it has an associated path, and that path
    /// isn't one of SC4's protected core game data files (<see cref="ProtectedFileNames"/>),
    /// which can only ever be written to via "Save As..." to a new file.
    /// </summary>
    public bool CanSaveInPlace =>
        CurrentFile is not null && CurrentPath is not null && !ProtectedFileNames.IsProtected(CurrentPath);

    /// <summary>True if the currently open file is one of SC4's protected core game data files.</summary>
    public bool IsCurrentFileProtected => ProtectedFileNames.IsProtected(CurrentPath);

    /// <summary>True if any entry in the currently open package already has this exact TGI - used
    /// for conflict checks (e.g. "Change Instance", Ilive Reader's DlgChangeInstance) before
    /// applying a new TGI, something the original dialog never actually checked for.</summary>
    public bool TgiExists(TGI tgi) =>
        CurrentFile is not null && CurrentFile.ListOfEntries.Any(e =>
            e.TGI.TypeID == tgi.TypeID && e.TGI.GroupID == tgi.GroupID && e.TGI.InstanceID == tgi.InstanceID);

    private static readonly Lazy<ConstructorInfo?> UnknownEntryCtor = new(() =>
    {
        var type = typeof(DBPFEntry).Assembly.GetType("csDBPF.DBPFEntryUnknown");
        return type is null ? null : FindReadingConstructor(type);
    });

    /// <summary>
    /// Adds a brand-new entry built from raw bytes and an explicit TGI - used by "Insert Batch"
    /// and "Insert Template" (Ilive Reader's DlgInsertBatch/DlgTemplate) to add entries that
    /// don't come from copying an existing one (that's <see cref="AddEntryFromClipboard"/>'s job).
    /// Always constructed as csDBPF's generic/fallback entry type - the same one
    /// <see cref="AddEntryFromClipboard"/> already relies on for entries with no structured
    /// decoder - rather than guessing a format-specific class from the TGI. A freshly-inserted
    /// entry gets its correct concrete type back automatically the next time the package is
    /// saved and reopened (exactly like any file csDBPF reads from disk); until then, tools
    /// that need a specific type (Exemplar property grid, image preview, ...) won't recognize
    /// it, while TGI/raw-bytes-driven tools (S3D/LUA editors, export, hex view) work immediately.
    /// </summary>
    /// <param name="tgi">TGI for the new entry.</param>
    /// <param name="rawBytes">Uncompressed payload bytes.</param>
    /// <param name="compress">If true, QFS-compresses <paramref name="rawBytes"/> before storing them.</param>
    public DBPFEntry? AddNewEntry(TGI tgi, byte[] rawBytes, bool compress)
    {
        var currentFile = CurrentFile;
        if (currentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var ctor = UnknownEntryCtor.Value;
        if (ctor is null)
        {
            return null;
        }

        var bytes = compress ? QFS.Compress(rawBytes) : rawBytes;
        if (bytes is null)
        {
            // QFS.Compress is annotated as returning byte[]? in csDBPF - guard against it
            // explicitly (CS8602) instead of a null-forgiving "!", which would only push a
            // NullReferenceException a few lines further down into a corrupted entry instead
            // of failing clearly here.
            throw new InvalidOperationException("QFS compression failed for the new entry's payload.");
        }

        object[] args = { tgi, 0u, (uint)bytes.Length, 0u, bytes };
        var newEntry = (DBPFEntry)ctor.Invoke(args);

        DbpfFileFixes.AddOrUpdateEntry(currentFile, newEntry);
        RecordedEntries.Add(newEntry);
        return newEntry;
    }

    /// <summary>
    /// Adds an entry whose raw bytes are already in their final on-disk form (compressed or
    /// not - whichever the bytes themselves already are) - used for "Insert Template", where
    /// the two bundled template blobs (blank Exemplar/Cohort) are stored exactly as Ilive
    /// Reader shipped them, one QFS-compressed and one not.
    /// </summary>
    public DBPFEntry? AddNewEntryRaw(TGI tgi, byte[] finalBytes)
    {
        var currentFile = CurrentFile;
        if (currentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var ctor = UnknownEntryCtor.Value;
        if (ctor is null)
        {
            return null;
        }

        object[] args = { tgi, 0u, (uint)finalBytes.Length, 0u, finalBytes };
        var newEntry = (DBPFEntry)ctor.Invoke(args);

        DbpfFileFixes.AddOrUpdateEntry(currentFile, newEntry);
        RecordedEntries.Add(newEntry);
        return newEntry;
    }

    /// <summary>
    /// Drops any stray Directory (DIR) subfile entry from the working set - Ilive Reader's
    /// manual "Reindex" (ID_MENU_REINDEX/CSave::ReIndex) recomputed each entry's index/order
    /// bookkeeping; this app's <see cref="DbpfWriter"/> already rebuilds that from scratch on
    /// every single save, so the only thing "Reindex" can meaningfully still do here is clear
    /// out a Directory entry that was loaded from disk and would otherwise just sit in the
    /// entry list unused until the next save silently replaces it anyway.
    /// </summary>
    /// <returns>Count of stray Directory entries removed.</returns>
    public int Reindex()
    {
        var currentFile = CurrentFile;
        if (currentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var stray = currentFile.ListOfEntries.Where(e =>
            e.TGI.TypeID == DbpfWriter.DirectoryTgi.TypeID
            && e.TGI.GroupID == DbpfWriter.DirectoryTgi.GroupID
            && e.TGI.InstanceID == DbpfWriter.DirectoryTgi.InstanceID).ToList();

        foreach (var entry in stray)
        {
            DbpfFileFixes.RemoveEntry(currentFile, entry.TGI);
        }

        return stray.Count;
    }

    /// <summary>
    /// Replaces an entry's raw payload with <paramref name="newBytes"/> (its TGI is kept
    /// unchanged). Used for "Import into entry..." - overwriting an existing entry's content from an
    /// external file, mirroring Ilive Reader's own file-replace concept. Uses the same
    /// reflective "recreate the entry with its (reading-existing) constructor" approach as
    /// <see cref="ChangeEntryTgi"/>, since <c>DBPFEntry.ByteData</c> has no confirmed public
    /// setter of its own - see the notes on <see cref="ChangeEntryTgi"/> for why.
    /// </summary>
    /// <returns>The new <see cref="DBPFEntry"/> instance that replaced <paramref name="entry"/>.</returns>
    public DBPFEntry ReplaceEntryBytes(DBPFEntry entry, byte[] newBytes)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        var tgi = entry.TGI;
        var entryType = entry.GetType();
        var ctor = FindReadingConstructor(entryType);

        if (ctor is null)
        {
            throw new NotSupportedException(
                $"Entries of type '{entryType.Name}' do not support importing new bytes.");
        }

        object[] args =
        {
            tgi,
            DbpfWriter.ToUInt32(entry.Offset),
            (uint)newBytes.Length,
            DbpfWriter.ToUInt32(entry.IndexPos),
            newBytes,
        };

        var newEntry = (DBPFEntry)ctor.Invoke(args);

        DbpfFileFixes.RemoveEntry(CurrentFile, tgi);
        CurrentFile.AddEntry(newEntry);
        RecordedEntries.Remove(entry);
        RecordedEntries.Add(newEntry);

        return newEntry;
    }

    // ---------------------------------------------------------------
    // Exemplar/Cohort property editing (Aggiungi/Modifica/Rimuovi)
    // ---------------------------------------------------------------

    /// <summary>
    /// Adds a new property to an exemplar/cohort, or updates it in place if a property with
    /// the same ID already exists, then rebuilds the entry's raw bytes so the change is
    /// reflected the next time the package is saved. Compression state is preserved
    /// automatically (re-encoded with whatever <see cref="DBPFEntry.IsCompressed"/> the
    /// entry already had), consistent with the rest of the app never requiring a manual
    /// "recompress" step.
    /// </summary>
    public void AddOrUpdateProperty(DBPFEntryEXMP exemplar, DBPFProperty property)
    {
        exemplar.AddOrUpdateProperty(property);
        ReencodePreservingCompression(exemplar);
        RecordedEntries.Add(exemplar);
    }

    /// <summary>Removes a property (if present) from an exemplar/cohort and rebuilds its raw bytes.</summary>
    public void RemoveProperty(DBPFEntryEXMP exemplar, uint propertyId)
    {
        exemplar.RemoveProperty(propertyId);
        ReencodePreservingCompression(exemplar);
        RecordedEntries.Add(exemplar);
    }

    private static void ReencodePreservingCompression(DBPFEntryEXMP exemplar)
    {
        ExemplarEncodeFix.EnsureEncodable(exemplar);
        exemplar.Encode(exemplar.IsCompressed);
    }

    /// <summary>
    /// Wipes every property currently on <paramref name="exemplar"/> and replaces it with
    /// exactly <paramref name="properties"/>, then rebuilds its raw bytes. Used by the T21
    /// Editor's SAVE instead of a series of individual AddOrUpdateProperty/RemoveProperty
    /// calls: a T21 (network lot / Prop&amp;Flora) Exemplar is exactly the kind of
    /// array-property-heavy entry where csDBPF's own decode can leave implausible leftover
    /// property IDs in <see cref="DBPFEntryEXMP.ListOfProperties"/> (see
    /// <see cref="ExemplarBinaryParser"/>'s remarks) - starting from a clean slate on every
    /// save, exactly like Jondor's own T21 Editor does (<c>ex.clearProperties()</c> then
    /// re-adding every property from scratch), guarantees the file written out matches only
    /// what the T21 Editor's own fields say, with nothing stale left over from whatever
    /// csDBPF originally (mis-)decoded.
    /// </summary>
    public void ReplaceAllProperties(DBPFEntryEXMP exemplar, IEnumerable<DBPFProperty> properties)
    {
        exemplar.Decode();
        exemplar.RemoveAllProperties();
        foreach (var property in properties)
        {
            exemplar.AddOrUpdateProperty(property);
        }

        ReencodePreservingCompression(exemplar);
        RecordedEntries.Add(exemplar);
    }

    // ---------------------------------------------------------------
    // QFS (re)compression
    // ---------------------------------------------------------------

    /// <summary>
    /// Sets the compression state of a single entry's payload, rebuilding its raw
    /// <c>ByteData</c> via QFS as needed. This is what "ricompressione/QFS" refers to:
    /// csDBPF's <c>DBPFEntry.Encode(bool compress)</c> internally calls into the QFS
    /// (RefPack/LZ77) codec (<see cref="csDBPF.QFS"/>) to compress or decompress the
    /// entry's serialized bytes before they are written back to disk.
    /// </summary>
    /// <param name="entry">Entry to (de)compress.</param>
    /// <param name="compress"><see langword="true"/> to QFS-compress; <see langword="false"/> to store uncompressed.</param>
    /// <returns>The entry's resulting <see cref="DBPFEntry.IsCompressed"/> state after the operation.</returns>
    public bool? SetEntryCompression(DBPFEntry entry, bool compress)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        // Make sure the entry's decoded object model is populated before re-encoding it -
        // Encode() serializes "the current state of the entry's data object", so a fresh
        // Decode() first guarantees that state actually reflects the on-disk payload.
        entry.Decode();

        // See ExemplarEncodeFix: Exemplar/Cohort entries need their csDBPF-internal
        // _isDecoded flag forced true before Encode() or it silently no-ops.
        if (entry is DBPFEntryEXMP exemplar)
        {
            ExemplarEncodeFix.EnsureEncodable(exemplar);
        }

        entry.Encode(compress);

        return entry.IsCompressed;
    }

    /// <summary>
    /// Applies <see cref="SetEntryCompression"/> to every entry currently in the package.
    /// Used for "comprimi/decomprimi tutto" bulk operations. Entries that fail to decode
    /// or encode (e.g. unsupported/corrupt payloads) are skipped and counted as failures
    /// rather than aborting the whole batch.
    /// </summary>
    /// <param name="compress"><see langword="true"/> to QFS-compress every entry; <see langword="false"/> to decompress every entry.</param>
    /// <returns>Count of entries successfully processed and count of entries that failed.</returns>
    public (int succeeded, int failed) SetAllEntriesCompression(bool compress)
    {
        if (CurrentFile is null)
        {
            throw new InvalidOperationException("No package is currently open.");
        }

        int succeeded = 0;
        int failed = 0;

        foreach (var entry in CurrentFile.ListOfEntries.ToList())
        {
            try
            {
                entry.Decode();

                // See ExemplarEncodeFix: Exemplar/Cohort entries need their csDBPF-internal
                // _isDecoded flag forced true before Encode() or it silently no-ops.
                if (entry is DBPFEntryEXMP exemplar)
                {
                    ExemplarEncodeFix.EnsureEncodable(exemplar);
                }

                entry.Encode(compress);
                succeeded++;
            }
            catch
            {
                failed++;
            }
        }

        return (succeeded, failed);
    }
}
